### ISSUE TITLE
BlasII.ModdingReferences does not exist anymore

### ISSUE THREAD

**Issue by Earthgames** [BrandenEK/BlasII.Randomizer#90]
The ` BlasII.ModdingReferences` does not exist any more on nuget, and building this is now impossible.
I tried removing it and look where in the code it was used, but dotnet did not agree that I removed it form the .csproj.
Any help to fix this would be appreciated

**Comment by BrandenEK** [comment]
That package was deleted and replaced with "BlasII.GameLibs" (v1.1.0).  I haven't got around to the randomizer yet since I am still working on the modding API first.  If you build the API from the commit where the references were changed (Or manually change them from the release state), then in the Randomizer csproj reference that dll instead of the nuget version (And change the references here) it would work.  That would be temporary, and hopefully soon I will have all blas2 mods updated to reference the new gamelibs package.

**Comment by Earthgames** [comment]
Cool, will wait on this
